const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../app.js'), 'utf8');
new vm.Script(source);
const start = source.indexOf("  let alcoholMapView = 'matrix';");
const end = source.indexOf('  function renderAlcoholWeekHeatmap(', start);
let draws = 0;
const canvas = { dataset: {}, getContext: () => ({createImageData: (w,h) => ({data:new Uint8ClampedArray(w*h*4)}),putImageData: () => draws++}) };
const buttons = ['matrix','heatmap'].map(view => ({dataset:{view},setAttribute(key,value){this[key]=value;}}));
let density = false;
let values = Array(77).fill(0); values[3*11+5] = 4;
const rows = Array.from({length:7},(_,r)=>({querySelectorAll:()=>values.slice(r*11,r*11+11).map(v=>({textContent:String(v)}))}));
const target = {querySelector:()=>canvas,querySelectorAll:s=>s==='.alcohol-map-row'?rows:buttons,classList:{toggle:(name,value)=>{density=value;}}};
const ctx=vm.createContext({els:{alcoholHeatmapVisual:target}});
vm.runInContext(source.slice(start,end),ctx);
ctx.setAlcoholMapView('matrix');assert.equal(draws,0,'matrix does no raster work');
ctx.setAlcoholMapView('heatmap');assert.equal(draws,1);assert.equal(density,true);assert.equal(buttons[1]['aria-pressed'],'true');
ctx.setAlcoholMapView('matrix');ctx.setAlcoholMapView('heatmap');assert.equal(draws,1,'toggle reuses canvas');
const image=ctx.alcoholDensityPixels(values,11);
assert.equal(image.width,264);assert.equal(image.height,168);
assert.strictEqual(ctx.alcoholDensityPixels(values,11),image,'re-renders reuse density buffer');
const at=(x,y)=>Array.from(image.pixels.slice((y*image.width+x)*4,(y*image.width+x)*4+3));
assert.ok(at(132,84)[0]>at(0,0)[0]);assert.ok(at(132,84)[1]<at(0,0)[1]);
const empty=ctx.alcoholDensityPixels(Array(77).fill(0),11);assert.deepEqual(Array.from(empty.pixels.slice(0,4)),[207,236,192,255]);
const before=performance.now();
for(let i=0;i<20;i++)ctx.alcoholDensityPixels(Array.from({length:77},(_,j)=>(j+i)%5),11);
console.log(`Density checks passed; cold dense raster mean: ${((performance.now()-before)/20).toFixed(2)} ms; cached toggles perform no draw.`);
