const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const source = fs.readFileSync(path.join(root, 'modules/points-details.js'), 'utf8');
const context = { window: { addEventListener() {} }, document: { addEventListener() {} } };
vm.createContext(context);
vm.runInContext(source.replace('})(window, document);', 'window.test = { groupRows, renderDay }; })(window, document);'), context);
const { groupRows, renderDay } = context.window.test;
const now = new Date(2026, 8, 13, 15);
const row = (points, date, extra = {}) => ({ points, earned_at: date, source_type: 'habit', reason: 'Lesen', ...extra });
const rows = [row(50, '2026-09-13T09:00:00'), row(-20, '2026-09-13T12:00:00'), row(10, '2026-09-07T00:00:00'), row(99, '2026-09-06T23:59:59'), row(7, 'bad'), row(30, '2026-09-14T01:00:00', { day: '2026-09-13' })];
const week = groupRows(rows, '7', now);
assert.equal(week.length, 2);
assert.equal(week[0].total, 60);
assert.equal(week[0].plus, 80);
assert.equal(week[0].minus, -20);
assert.equal(week[1].total, 10, 'include the complete first calendar day');
assert.equal(groupRows(rows, 'all', now).reduce((sum, day) => sum + day.total, 0), 176, 'unknown dates remain in all-time reconciliation');
const many = Array.from({ length: 120 }, () => row(2, '2026-09-13T10:00:00'));
assert.equal(groupRows(many, 'all', now)[0].total, 240, 'never truncate ledger totals');
assert.equal(groupRows(many, 'all', now)[0].rows.length, 120);
assert.equal(groupRows([], 'all', now).length, 0);
assert.equal(groupRows([row(-300, '2026-09-13')], 'all', now)[0].total, -300);
const html = renderDay(groupRows([row(2, '2026-09-13', { reason: '<img src=x onerror=alert(1)>' })], 'all', now)[0], true);
assert.ok(html.includes('&lt;img'));
assert.ok(!html.includes('<img'));
// Exercise the actual application snapshot against its total and pause filter.
const snapshotCode = app.match(/  window.HabitFlowPointsLive = Object.freeze\(\{[\s\S]*?\n  \}\);/)[0];
const ledger = [row(100, '2026-09-13', { source_id: 'a' }), row(-20, '2026-09-13', { source_id: 'b' }), row(900, '2026-09-13', { paused: true }), row(60, '2026-09-14T01:59:00', { source_type: 'bonus', source_id: 'smoke-daily-bonus-2026-09-13' }), row(-50, '2026-09-12', { source_type: 'bonus', source_id: 'alcohol', reason: 'Alkohol-Tag: Stark' })];
const snapshotContext = { window: {}, state: { pointsLedger: ledger, alcoholLogs: [{ id: 'alcohol', log_date: '2026-09-11' }] }, visibleLedgerPoints: () => ledger.filter(row => !row.paused), getTotalPoints: () => 90, evolutionStageFromPoints: total => ({ stage: 1, nextPoints: 250 - total }), smokeDailyBonusDay: row => row.source_id.replace('smoke-daily-bonus-', ''), isSmokeDailyBonusEntry: row => row.source_id?.startsWith('smoke-daily-bonus-'), isAlcoholPointsEntry: row => row.source_id === 'alcohol' };
vm.runInNewContext(snapshotCode, snapshotContext);
const snapshot = snapshotContext.window.HabitFlowPointsLive.snapshot();
assert.equal(snapshot.rows.reduce((sum, row) => sum + row.points, 0), snapshot.total);
assert.equal(snapshot.rows.length, 4);
assert.equal(snapshot.rows[2].day, '2026-09-13');
assert.equal(snapshot.rows[3].day, '2026-09-11');
snapshot.rows[0].points = 999;
assert.equal(ledger[0].points, 100, 'snapshot cannot mutate live ledger');
console.log('Points details: date boundaries, totals, pauses, attribution, escaping and snapshot checks passed');
